#!/usr/bin/env bash
#
# A simple bash script to import all MySQL backup.
#
# @author
#   Gerald Z. Villorente
#
#
backup_directory=$1
cd $backup_directory
for f in * ; do
  name=${f%.sql}
  mysqladmin -u root create ${name##*/}
  mysql -u root ${name##*/} < $f
done
